# spot-cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop    # Name of your EKS cluster
  region: us-east-1  # AWS region where the cluster will be created

managedNodeGroups:
- name: spot       # Name of the node group
  instanceTypes: ["c3.large","c4.large","c5.large","c5d.large","c5n.large","c5a.large"]   # Allowed EC2 instance types for spot instances
  #instanceTypes: ["t3.medium", "t3.large", "c5.large", "c5d.large", "c5n.large", "c5a.large"]
  spot: false           # Enables Spot instances
  desiredcapacity: 1   # Number of nodes desired initially
